apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: airfactoryservices.cory.github.com
spec:
  group: cory.github.com
  names:
    kind: AirFactoryService
    listKind: AirFactoryServiceList
    plural: airfactoryservices
    singular: airfactoryservice
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: AirFactoryService is the Schema for the airfactoryservices API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AirFactoryServiceSpec defines the desired state of AirFactoryService
            type: object
          status:
            description: AirFactoryServiceStatus defines the observed state of AirFactoryService
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
